DROP TABLE IF EXISTS `product_category`;
DROP TABLE IF EXISTS `cart_item`;
DROP TABLE IF EXISTS `product`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `payment`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `order_item`;
DROP TABLE IF EXISTS `transaction_history`;
DROP TABLE IF EXISTS `review`;
DROP TABLE IF EXISTS `review_image`;
DROP TABLE IF EXISTS `image`;

CREATE TABLE IF NOT EXISTS `product` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    thumbnail_url VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    short_description VARCHAR(255) DEFAULT NULL,
    price DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS `category` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_name(name)
);

CREATE TABLE IF NOT EXISTS `product_category` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_product_id_category_id (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS `orders` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_key VARCHAR(150) NOT NULL,
    total_price DECIMAL(15, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_order_key (order_key)
);

CREATE TABLE IF NOT EXISTS `order_item` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    quantity BIGINT NOT NULL,
    unit_price DECIMAL(15, 2) NOT NULL,
    total_price DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_order_id_product_id (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS `cart_item` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_user_id_product_id (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS `payment` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    external_payment_key VARCHAR(150) DEFAULT NULL,
    method VARCHAR(150) DEFAULT NULL,
    paid_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_order_id (order_id)
);

CREATE TABLE IF NOT EXISTS `transaction_history` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    external_payment_key VARCHAR(150) DEFAULT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    message VARCHAR(255) DEFAULT NULL,
    occurred_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_transaction_history_order_id (order_id)
);

CREATE TABLE IF NOT EXISTS `review` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    review_key VARCHAR(150) NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    rate DECIMAL(2,1) NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_user_id_review_key (user_id, review_key)
);

CREATE TABLE IF NOT EXISTS `image` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_user_id_image_url (user_id, image_url)
);

CREATE TABLE IF NOT EXISTS `review_image` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    image_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    UNIQUE KEY uk_review_id_image_id (review_id, image_id)
);
