DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;

CREATE TABLE IF NOT EXISTS product(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    thumbnail_url VARCHAR(255) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    short_description VARCHAR(255) NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '컬럼 상태'
);

CREATE TABLE IF NOT EXISTS category(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '컬럼 상태'
);

CREATE TABLE IF NOT EXISTS product_category(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    state VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '컬럼 상태',

    UNIQUE KEY uk_product_id_category_id (product_id, category_id)
);